version: '3'

services:
  phpfpm:
    build: ./.docker/images/php-fpm
    expose:
      - 9000
    volumes:
      - ./.docker/images/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./.docker/images/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html

  nginx-app:
    image: nginx
    depends_on:
      - phpfpm
      - db
    ports:
      - "80:80"
    links:
      - phpfpm
      - db
    volumes:
      - ./.docker/images/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LETSENCRYPT_HOST: $LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./.docker/data/mysql/:/docker-entrypoint-initdb.d
      - data_volume:/var/lib/mysql

  composer:
    build:
      context: ./
      dockerfile: ./.docker/images/composer/Dockerfile
    working_dir: /var/www/html
    command: install -v
    volumes:
      - ./app:/var/www/html

  node:
    depends_on:
      - phpfpm
      - nginx-app
    image: node:8.1
    command: bash -c "cd /var/www/html && yarn upgrade && yarn install && node node_modules/node-sass/scripts/install.js;"
    volumes:
      - ./app:/var/www/html

volumes:
  data_volume:

networks:
  default:
    external:
      name: nginx-proxy
